### ISSUE TITLE
License issue

### ISSUE THREAD

**Issue by n-rodriguez** [streamich/thingies#48]
Hi there!

There is an issue with the project license : 

* `package.json` says `Unlicense` (https://github.com/streamich/thingies/blob/main/package.json#L15)
* `LICENSE` file says `MIT` (https://github.com/streamich/thingies/blob/main/LICENSE)

Which one is the right one? Thank you!

**Comment by n-rodriguez** [comment]
Ping @streamich

**Comment by n-rodriguez** [comment]
Ping @streamich

**Comment by streamich** [comment]
Thanks, fixed!
